FANTASY_PAGE_SELECT_REGISTER = 0E8h
FANTASY_PAGE_SET_REGISTER = 0EAh
FANTASY_PAGE_OFFSET_AMT = 034h

PAGE_FRAME_COUNT = 28
MAX_PAGE_COUNT = PAGE_COUNT_4_MB

FANTASY_CHIPSET_CONVENTIONAL_PAGE_4000 = 12
FANTASY_CHIPSET_CONVENTIONAL_PAGEFRAME_DELTA = 4