
; 1Ch for D000. 18h for C000 if we were to use that.
HT18_PAGE_REGISTER_OFFSET = 01Ch
HT18_MEMORY_CONFIG_REGISTER = 00h
HT18_EXTENDED_BOUNDARY_CONFIG_REGISTER = 03h
HT18_CHIPSET_CONFIG_REGISTER_SELECT = 1EDh
HT18_CHIPSET_CONFIG_REGISTER_READWRITE = 1EFh
; todo correct?
HT18_PAGE_OFFSET_AMT = 0280h
HT18_PAGE_SELECT_REGISTER = 01EEh
HT18_PAGE_SET_REGISTER = 01ECh
PAGE_FRAME_COUNT = 28
HT18_CHIPSET_UNMAP_VALUE = 0000h
DEFAULT_CONVENTIONAL_PAGE_COUNT = 24
CHIPSET_PAGE_FRAME_COUNT = 32
MAX_PAGE_COUNT = PAGE_COUNT_15_MB


;MAX_CONTEXT_COUNT = 2
MAX_CONTEXT_COUNT = 0

; page 0x4000 is 4 in EMS api but 0 in chipset
HT18_CHIPSET_CONVENTIONAL_PAGEFRAME_DELTA = 4

HT18_PAGE_C000_REGISTER_OFFSET = 018h

; insert a 1 into bit 9
HT18_ENABLE_ON_MACRO MACRO
    ror ah, 1
    stc
    rcl ah, 1
    rcl ah, 1

ENDM

; insert a 0 into bit 9 (actually just write 0 in practice.)
HT18_ENABLE_OFF_MACRO MACRO
    ror ah, 1
    clc
    rcl ah, 1
    rcl ah, 1
ENDM

CHIPSET_DEFAULT_OFFSET = HT18_PAGE_OFFSET_AMT
