LOTECH_BASE_PAGE_REGISTER = 0260h

LOTECH_CHIPSET_UNMAP_VALUE = 0FFh
PAGE_FRAME_COUNT = 4
MAX_PAGE_COUNT = PAGE_COUNT_2_MB
DEFAULT_CONVENTIONAL_PAGE_COUNT = 0
MAX_CONTEXT_COUNT = 0
CHIPSET_PAGE_FRAME_COUNT = 4

CHIPSET_DEFAULT_OFFSET = 0
