NEAT_CHIPSET_CONFIG_REGISTER_SELECT = 022h
NEAT_CHIPSET_CONFIG_REGISTER_READWRITE = 023h
NEAT_CHIPSET_ADDRESS_EXTENSION_REGISTER = 06Eh
NEAT_PAGE_REGISTER_0 = 00208h
NEAT_PAGE_REGISTER_1 = 04208h
NEAT_PAGE_REGISTER_2 = 08208h
NEAT_PAGE_REGISTER_3 = 0C208h
NEAT_PAGE_ENABLE_FLAG = 080h  ; enable flag
NEAT_PAGE_OFFSET_AMT = 080h   ; offset 1MB todo selfmodify

; no real unmap support?

PAGE_FRAME_COUNT = 4

MAX_PAGE_COUNT = PAGE_COUNT_2_MB  ; todo: selfmodify
DEFAULT_CONVENTIONAL_PAGE_COUNT = 0
MAX_CONTEXT_COUNT = 0
CHIPSET_PAGE_FRAME_COUNT = 4
