NEAT_CHIPSET_CONFIG_REGISTER_SELECT = 022h
NEAT_CHIPSET_CONFIG_REGISTER_READWRITE = 023h
NEAT_CHIPSET_ADDRESS_EXTENSION_REGISTER = 06Eh
NEAT_PAGE_REGISTER_0 = 00208h
NEAT_PAGE_REGISTER_1 = 04208h
NEAT_PAGE_REGISTER_2 = 08208h
NEAT_PAGE_REGISTER_3 = 0C208h
NEAT_PAGE_OFFSET_AMT = 080h  ; enable flag

; no real unmap support?
NEAT_CHIPSET_UNMAP_VALUE = 7Fh
PAGE_FRAME_COUNT = 4
; todo: support > 2MB via 2nd set of port hits.
MAX_PAGE_COUNT = PAGE_COUNT_2_MB
DEFAULT_CONVENTIONAL_PAGE_COUNT = 0
MAX_CONTEXT_COUNT = 0
CHIPSET_PAGE_FRAME_COUNT = 4
