NEAT_CHIPSET_CONFIG_REGISTER_SELECT = 022h
NEAT_CHIPSET_CONFIG_REGISTER_READWRITE = 023h
NEAT_CHIPSET_DRAM_CONFIG_REGISTER = 06Bh
NEAT_CHIPSET_DRAM_CONFIG_REGISTER_EMS_ENABLE_BIT = 010h
NEAT_CHIPSET_MEMORY_SIZE_BANK01_REGISTER = 06Ah
NEAT_CHIPSET_MEMORY_SIZE_BANK23_REGISTER = 06Ch
NEAT_CHIPSET_EMS_CONFIG_REGISTER = 06Dh
NEAT_CHIPSET_ADDRESS_EXTENSION_REGISTER = 06Eh
NEAT_CHIPSET_EMS_SIZE_REGISTER = 06Fh
NEAT_PAGE_REGISTER_0 = 00208h
NEAT_PAGE_REGISTER_1 = 04208h
NEAT_PAGE_REGISTER_2 = 08208h
NEAT_PAGE_REGISTER_3 = 0C208h
NEAT_PAGE_ENABLE_FLAG = 080h  ; enable flag
NEAT_PAGE_OFFSET_AMT = 044h   ; 1MB + high memory area


; no real unmap support?

PAGE_FRAME_COUNT = 4

MAX_PAGE_COUNT = PAGE_COUNT_7_MB  ; technically 8 mb is pageable if we include conventional?
DEFAULT_CONVENTIONAL_PAGE_COUNT = 0
MAX_CONTEXT_COUNT = 0
CHIPSET_PAGE_FRAME_COUNT = 4

CHIPSET_DEFAULT_OFFSET = NEAT_PAGE_OFFSET_AMTs
