SCAMP_PAGE_OFFSET_AMT = 68h
SCAMP_PAGE_SELECT_REGISTER = 0E8h
SCAMP_PAGE_SET_REGISTER = 0EAh
MAX_PAGE_COUNT = PAGE_COUNT_4_MB
PAGE_FRAME_COUNT = 36 ; todo 32
DEFAULT_CONVENTIONAL_PAGE_COUNT = 24
MAX_CONTEXT_COUNT = 0
