SCAMP_PAGE_SELECT_REGISTER = 0E8h
SCAMP_PAGE_SET_REGISTER = 0EAh

SCAMP_PAGE_OFFSET_AMT = 044h

CHIPSET_PAGE_FRAME_COUNT = 36
PAGE_FRAME_COUNT = 28
MAX_PAGE_COUNT = PAGE_COUNT_15_MB


SCAMP_CHIPSET_CONVENTIONAL_PAGE_4000 = 12
SCAMP_CHIPSET_CONVENTIONAL_PAGEFRAME_DELTA = 4

DEFAULT_CONVENTIONAL_PAGE_COUNT = 24

MAX_CONTEXT_COUNT = 4