
; 18h for D000. 1Ch for E000 if we were to use that.
SCAT_PAGE_C000_REGISTER_OFFSET = 014h
SCAT_CHIPSET_AUTOINCREMENT_FLAG = 080h
SCAT_CHIPSET_CONFIG_REGISTER_SELECT = 022h
SCAT_CHIPSET_CONFIG_REGISTER_READWRITE = 023h
SCAT_DRAM_CONFIGURATION_REGISTER = 04Dh
SCAT_EXTENDED_BOUNDARY_REGISTER = 04Eh
SCAT_EMS_CONFIG_REGISTER = 04Fh
SCAT_PAGE_SELECT_REGISTER = 020Ah
SCAT_PAGE_SET_REGISTER = 0208h


; 8000 is to mark bit 15 for free "ems enabled"
; 0080 is [currently hardcoded] 2 MB offset for beginning of EMS pagination,
SCAT_PAGE_ENABLE_BIT = 08000h
SCAT_PAGE_OFFSET_AMT = 08080h
SCAT_CHIPSET_UNMAP_VALUE = 03FFh

; use chipset value
; todo should be 15 mb
MAX_PAGE_COUNT = PAGE_COUNT_15_MB
;MAX_PAGE_COUNT = PAGE_COUNT_4_MB
PAGE_FRAME_COUNT = 28


SCAT_CHIPSET_CONVENTIONAL_PAGEFRAME_DELTA = 4