; for standard lim ems 3.2 style boards with page frame and usually 2 mb.
; this can be 208h, 218h, etc... todo parse port, etc
STANDARD_BOARD_PAGE_REGISTER_0 = 00208h
STANDARD_BOARD_PAGE_REGISTER_1 = 04208h
STANDARD_BOARD_PAGE_REGISTER_2 = 08208h
STANDARD_BOARD_PAGE_REGISTER_3 = 0C208h
STANDARD_BOARD_PAGE_ON_BIT = 080h
PAGE_FRAME_COUNT = 4
; no real unmap support?
STANDARD_BOARD_UNMAP_VALUE = 00h
STANDARD_BOARD_CONST_PAGE_COUNT = PAGE_COUNT_2_MB
MAX_PAGE_COUNT = PAGE_COUNT_2_MB
CHIPSET_PAGE_FRAME_COUNT = 4
STANDARD_BOARD_CONST_PAGE_COUNT = 4

DEFAULT_CONVENTIONAL_PAGE_COUNT = 0
MAX_CONTEXT_COUNT = 0
